### ISSUE TITLE
'summarize-by' parameter not supported

### ISSUE THREAD

**Issue by ccaum** [puppetlabs/puppetdb-ruby#9]
The event-counts endpoint requires the 'summarize-by' parameter. However, when I specify that parameter, PuppetDB fails saying the parameter wasn't passed to it.
For example:

client.request( 'event-counts', [:and, [:'<', 'timestamp', Time.now ], [:'>', 'timestamp', 2.days.ago], {:'summarize-by' => 'resource'}] )

**Comment by nemski** [comment]
Your code should look like this:

````ruby
client.request( 'event-counts',
  [:and,
    [:'<', 'timestamp', Time.now ],
    [:'>', 'timestamp', 2.days.ago],
  ],
  {:'summarize-by' => 'resource'}
)
```

Notice the summarize-by is outside the query array, it's a separate parameter.

**Comment by ccaum** [comment]
Ah, thanks @nemski
